"""Fixed relationship insights

Revision ID: 1ffe0be0d3be
Revises: 48bb8b06ce40
Create Date: 2024-03-22 14:34:52.180486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffe0be0d3be'
down_revision = '48bb8b06ce40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insights_actions_actions', type_='foreignkey')
        batch_op.drop_column('actions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actions', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_insights_actions_actions', 'actions', ['actions'], ['id'])

    # ### end Alembic commands ###
