"""Updated goals and peronal goals

Revision ID: 24dec93a25c5
Revises: 207128732a2b
Create Date: 2024-03-22 12:38:40.105979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dec93a25c5'
down_revision = '207128732a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_saved', sa.Float(), nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_income', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_expenses', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('personal_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_saved', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_goals', schema=None) as batch_op:
        batch_op.drop_column('amount_saved')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('total_expenses')
        batch_op.drop_column('total_income')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('amount_saved')

    # ### end Alembic commands ###
