"""Added action table and relationships to insight

Revision ID: 48bb8b06ce40
Revises: 711cc6fffe0f
Create Date: 2024-03-22 14:18:31.781997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bb8b06ce40'
down_revision = '711cc6fffe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('insight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_actions_insight_id_insights')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.alter_column('actions',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_insights_actions_actions'), 'actions', ['actions'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_insights_actions_actions'), type_='foreignkey')
        batch_op.alter_column('actions',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.drop_table('actions')
    # ### end Alembic commands ###
