"""Changed user models and group model to better reflect relationship

Revision ID: 6d674d97ecc1
Revises: 812e1daaa4fc
Create Date: 2024-03-16 13:40:53.363291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d674d97ecc1'
down_revision = '812e1daaa4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_groups_user_id_users', type_='foreignkey')
        batch_op.drop_column('visibility_status')
        batch_op.drop_column('role')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('visibility_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('income', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['first_name'])
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.create_foreign_key(batch_op.f('fk_users_group_id_groups'), 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_group_id_groups'), type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('group_id')
        batch_op.drop_column('income')
        batch_op.drop_column('rent')
        batch_op.drop_column('visibility_status')
        batch_op.drop_column('role')
        batch_op.drop_column('admin')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('visibility_status', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key('fk_groups_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
