"""Updated models will test data

Revision ID: 702d5f474da1
Revises: 9bfa8691f614
Create Date: 2024-03-12 11:48:54.974394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702d5f474da1'
down_revision = '9bfa8691f614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
