"""JI - added restful CRUD routes to models

Revision ID: 715f35897bc7
Revises: 1ffe0be0d3be
Create Date: 2024-03-23 12:22:39.227557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715f35897bc7'
down_revision = '1ffe0be0d3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('end_timeframe',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_family')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.alter_column('savings_monthly',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('savings_needed',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('strategy',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('personal_goals', schema=None) as batch_op:
        batch_op.alter_column('end_timeframe',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_goals', schema=None) as batch_op:
        batch_op.alter_column('end_timeframe',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.alter_column('strategy',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('savings_needed',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('savings_monthly',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_family', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('end_timeframe',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
