"""added new user columns

Revision ID: 812e1daaa4fc
Revises: f834d07ed58c
Create Date: 2024-03-15 18:27:57.371142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812e1daaa4fc'
down_revision = 'f834d07ed58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('_totp_secret', sa.String(), nullable=True))
        batch_op.drop_column('access_token')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_totp_secret')
        batch_op.drop_column('_access_token')

    # ### end Alembic commands ###
