"""Created insights table and added new columns

Revision ID: ed7266a6dcf6
Revises: 2d365729906d
Create Date: 2024-03-21 12:04:55.765304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7266a6dcf6'
down_revision = '2d365729906d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_monthly', sa.Float(precision=2), nullable=True))
        batch_op.add_column(sa.Column('savings_needed', sa.Float(precision=2), nullable=True))
        batch_op.add_column(sa.Column('strategy', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('actions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_insights_group_id_groups', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_insights_goal_id_goals'), 'goals', ['goal_id'], ['id'])
        batch_op.drop_column('text')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_insights_goal_id_goals'), type_='foreignkey')
        batch_op.create_foreign_key('fk_insights_group_id_groups', 'groups', ['group_id'], ['id'])
        batch_op.drop_column('goal_id')
        batch_op.drop_column('actions')
        batch_op.drop_column('strategy')
        batch_op.drop_column('savings_needed')
        batch_op.drop_column('savings_monthly')

    # ### end Alembic commands ###
